# fuzzel — Gruvbox Material, minimal

[main]
font=JetBrainsMono Nerd Font:size=12
prompt="› "
terminal=kitty -e
icons-enabled=no
width=36
lines=10
horizontal-pad=20
vertical-pad=14
inner-pad=8

[colors]
# RRGGBBAA
background=282828f2
text=d4be98ff
prompt=a9b665ff
placeholder=7c6f64ff
input=d4be98ff
match=d8a657ff
selection=3c3836ff
selection-text=d4be98ff
selection-match=d8a657ff
border=a9b665ff

[border]
width=2
radius=6
